label:
  name: solar-system-qa

namespace: qa

deploy:
  name: solar-qa
  replicas: 1
  image: siddharth67/solar-system
  tag: 85a040728c458d3dea1e44285a4dba382ab7e93c
  port: 3000

service:
  name: solar-qa-test
  port: 80
  type: NodePort
  
