name: Solar-unit-test

on: 
    workflow_dispatch: {}

jobs:
    unit-test:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4

            - name: node-setup
              uses: actions/setup-node@v4
              with:
                node-version: '18'
                
            - name: install 
              run: npm install
              
            - name: Test
              run: npm test